apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: metallb-config
data:
  name: {{ .Values.name | quote }}
  ipRange: {{ .Values.ipRange | quote }}
