apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-environments
  namespace: open-cluster-management-policies
data:
  environments: |
    - name: redis-preprod-1
      ipRange: 192.168.1.10-192.168.1.15
    - name: redis-preprod-2
      ipRange: 192.168.1.20-192.168.1.25
    - name: redis-preprod-3
      ipRange: 192.168.1.30-192.168.1.35
