apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: metallb-placement-{{ .Values.env }}
  namespace: open-cluster-management-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            environment: {{ .Values.env }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: metallb-binding-{{ .Values.env }}
  namespace: open-cluster-management-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: metallb-placement-{{ .Values.env }}
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-metallb-{{ .Values.env }}
