environments:
  - name: redis-dev-1
    namespace: redis-ent-dev-operator
    ipRange: 10.1.1.10-10.1.1.15
  - name: redis-dev-2
    namespace: redis-ent-dev2-operator
    ipRange: 10.1.1.20-10.1.1.25
